// Copyright 2025 The PECOS Developers
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License
// is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
// or implied. See the License for the specific language governing permissions and limitations under
// the License.

/// Structured data for Record commands
///
/// This enum represents the various types of record data that can be
/// generated by quantum programs, including result records and key-value pairs.
///
/// # Variants
///
/// - `ResultRecord` - Record a measurement result with an optional label
/// - `KeyValueRecord` - Record a key-value pair for classical processing
/// - `RawRecord` - Raw record command for backward compatibility
///
/// # Examples
///
/// ```
/// use pecos_engines::core::record_data::RecordData;
///
/// // Create a result record with ID 0 and label "q0"
/// let result_record = RecordData::result(0, Some("q0".to_string()));
///
/// // Create a key-value record
/// let kv_record = RecordData::key_value("energy".to_string(), -1.5);
///
/// // Create a raw record
/// let raw_record = RecordData::RawRecord("RECORD data".to_string());
/// ```
#[derive(Debug, Clone, PartialEq)]
pub enum RecordData {
    /// Record a result with numeric ID and optional label
    ResultRecord(usize, Option<String>),

    /// Record a key-value pair for classical processing
    KeyValueRecord(String, f64),

    /// Raw record command for backward compatibility
    RawRecord(String),
}

impl RecordData {
    /// Create a new `ResultRecord` with a numeric ID and optional label
    ///
    /// # Arguments
    ///
    /// * `id` - The numeric ID of the result
    /// * `label` - An optional label for the result
    ///
    /// # Returns
    ///
    /// A new `RecordData::ResultRecord` variant
    #[must_use]
    pub fn result(id: usize, label: Option<String>) -> Self {
        RecordData::ResultRecord(id, label)
    }

    /// Create a new `KeyValueRecord` with a key and value
    ///
    /// # Arguments
    ///
    /// * `key` - The key for the record
    /// * `value` - The numeric value for the record
    ///
    /// # Returns
    ///
    /// A new `RecordData::KeyValueRecord` variant
    #[must_use]
    pub fn key_value(key: String, value: f64) -> Self {
        RecordData::KeyValueRecord(key, value)
    }
}
