//! Test integration between QIS programs and Selene runtime

use crate::engine::{SeleneClassicalControlEngine, SeleneEngineConfig};
use anyhow::Result;
use pecos_engines::engine_system::ClassicalEngine;
use std::path::PathBuf;

/// Test running a QIS program through the Selene runtime
#[allow(dead_code)]
pub fn test_qis_with_selene_runtime() -> Result<()> {
    let plugin_path = "/home/ciaranra/Repos/cl_projects/gup/selene/target/release/libselene_simple_runtime.so";
    let qis_program_path = "/home/ciaranra/Repos/cl_projects/gup/PECOS/test_programs/simple_qis.ll";

    println!("Setting up Selene runtime integration test...");

    // Configure the engine
    let config = SeleneEngineConfig {
        runtime_plugin_path: PathBuf::from(plugin_path),
        n_qubits: 5,
        verbose: true,
    };

    // Create the engine
    let mut engine = SeleneClassicalControlEngine::new(config)
        .map_err(|e| anyhow::anyhow!("Failed to create engine: {}", e))?;

    // Load the QIS program
    engine.load_llvm_ir(qis_program_path)
        .map_err(|e| anyhow::anyhow!("Failed to load QIS program: {}", e))?;

    println!("✅ Successfully configured Selene engine with QIS program");

    // Test generating commands (which initializes the runtime)
    let _message = engine.generate_commands()
        .map_err(|e| anyhow::anyhow!("Failed to generate commands: {}", e))?;

    println!("✅ Successfully generated ByteMessage from Selene runtime!");
    println!("Message generated successfully");

    // Test getting results
    let shot = engine.get_results()
        .map_err(|e| anyhow::anyhow!("Failed to get results: {}", e))?;

    println!("✅ Successfully got results from engine!");
    println!("Shot has {} data entries", shot.data.len());

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_qis_selene_integration() {
        match test_qis_with_selene_runtime() {
            Ok(()) => println!("✅ QIS-Selene integration test passed!"),
            Err(e) => {
                println!("❌ QIS-Selene integration test failed: {}", e);
                panic!("QIS-Selene integration test failed: {}", e);
            }
        }
    }
}