#!/usr/bin/env python3
"""Test PMIR compilation followed by execution using PECOS QIR engine.

This demonstrates the full pipeline: HUGR → PMIR → LLVM IR → Execution
"""

import json
import sys
import tempfile
from pathlib import Path

import pytest

sys.path.append("python/quantum-pecos/src")

try:
    from pecos_rslib import (
        compile_hugr_via_pmir,
        hugr_to_pmir_mlir,
        PMIR_AVAILABLE,
    )
except ImportError:
    PMIR_AVAILABLE = False

try:
    from pecos.engines.hybrid_engine import HybridEngine
    PECOS_AVAILABLE = True
except ImportError:
    PECOS_AVAILABLE = False


@pytest.mark.skipif(not PMIR_AVAILABLE, reason="PMIR not available")
@pytest.mark.skipif(not PECOS_AVAILABLE, reason="PECOS not available")
def test_pmir_compilation_and_execution():
    """Test compiling via PMIR and executing with PECOS."""
    # Create a simple quantum circuit HUGR
    hugr = {
        "version": "0.1.0",
        "name": "random_bit",
        "nodes": [
            {"op": {"type": "AllocQubit"}},
            {"op": {"type": "H"}},
            {"op": {"type": "Measure"}},
            {"op": {"type": "Output", "port": 0}}
        ],
        "edges": [
            {"src": [0, 0], "dst": [1, 0]},
            {"src": [1, 0], "dst": [2, 0]},
            {"src": [2, 0], "dst": [3, 0]}
        ]
    }
    
    hugr_json = json.dumps(hugr)
    
    # Convert to PMIR
    pmir_mlir = hugr_to_pmir_mlir(hugr_json, debug_output=False, optimization_level=2)
    print("\nGenerated PMIR:")
    print(pmir_mlir)
    
    # Try to compile to LLVM IR
    try:
        llvm_ir = compile_hugr_via_pmir(
            hugr_json, 
            debug_output=False, 
            optimization_level=2, 
            target_triple=None
        )
        print("\nGenerated LLVM IR (first 500 chars):")
        print(llvm_ir[:500] + "..." if len(llvm_ir) > 500 else llvm_ir)
        
        # Save LLVM IR to a temporary file
        with tempfile.NamedTemporaryFile(mode='w', suffix='.ll', delete=False) as f:
            f.write(llvm_ir)
            llvm_file = Path(f.name)
        
        try:
            # Note: The LLVM IR generated by PMIR uses standard QIR function names
            # which should be compatible with PECOS's QIR runtime
            
            # Verify the LLVM IR was generated correctly
            assert llvm_file.exists()
            assert llvm_file.stat().st_size > 0
            
            # Verify it contains expected QIR functions
            llvm_content = llvm_file.read_text()
            assert "@__quantum__rt__qubit_allocate" in llvm_content
            assert "@__quantum__qis__h__body" in llvm_content
            assert "@__quantum__qis__mz__body" in llvm_content
            assert "define i1 @main()" in llvm_content
            
            print(f"\n[PASS] Successfully compiled and saved LLVM IR to {llvm_file}")
            
            # TODO: To fully execute this, we would need to:
            # 1. Use pecos_rslib's QirEngine with the generated LLVM file
            # 2. Or integrate with PECOS's existing QIR execution infrastructure
            
        finally:
            # Clean up
            if llvm_file.exists():
                llvm_file.unlink()
                
    except RuntimeError as e:
        if "mlir-opt" in str(e) or "MLIR" in str(e):
            pytest.skip("MLIR tools not available")
        else:
            raise


@pytest.mark.skipif(not PMIR_AVAILABLE, reason="PMIR not available")
def test_bell_state_pmir_analysis():
    """Analyze a Bell state circuit compiled via PMIR."""
    hugr = {
        "version": "0.1.0",
        "name": "bell_state",
        "nodes": [
            {"op": {"type": "AllocQubit"}},
            {"op": {"type": "AllocQubit"}},
            {"op": {"type": "H"}},
            {"op": {"type": "CX"}},
            {"op": {"type": "Measure"}},
            {"op": {"type": "Measure"}},
            {"op": {"type": "Output", "port": 0}},
            {"op": {"type": "Output", "port": 1}}
        ],
        "edges": [
            {"src": [0, 0], "dst": [2, 0]},
            {"src": [2, 0], "dst": [3, 0]},
            {"src": [1, 0], "dst": [3, 1]},
            {"src": [3, 0], "dst": [4, 0]},
            {"src": [3, 1], "dst": [5, 0]},
            {"src": [4, 0], "dst": [6, 0]},
            {"src": [5, 0], "dst": [7, 0]}
        ]
    }
    
    hugr_json = json.dumps(hugr)
    
    # Compile via PMIR
    try:
        llvm_ir = compile_hugr_via_pmir(
            hugr_json,
            debug_output=False,
            optimization_level=2,
            target_triple=None
        )
        
        # Analyze the generated LLVM IR
        # Count quantum operations (only calls, not declarations)
        qubit_allocs = llvm_ir.count("call i8* @__quantum__rt__qubit_allocate")
        h_gates = llvm_ir.count("call void @__quantum__qis__h__body")
        cnot_gates = llvm_ir.count("call void @__quantum__qis__cnot__body")
        measurements = llvm_ir.count("call void @__quantum__qis__mz__body")
        
        print(f"\nBell State LLVM IR Analysis:")
        print(f"- Qubit allocations: {qubit_allocs}")
        print(f"- Hadamard gates: {h_gates}")
        print(f"- CNOT gates: {cnot_gates}")
        print(f"- Measurements: {measurements}")
        
        # Verify expected counts
        assert qubit_allocs == 2, "Should allocate 2 qubits"
        assert h_gates == 1, "Should have 1 Hadamard gate"
        assert cnot_gates == 1, "Should have 1 CNOT gate"
        assert measurements == 2, "Should have 2 measurements"
        
        print("\n[PASS] Bell state circuit compiled correctly via PMIR")
        
    except RuntimeError as e:
        if "mlir-opt" in str(e) or "MLIR" in str(e):
            pytest.skip("MLIR tools not available")
        else:
            raise


if __name__ == "__main__":
    # Run tests directly
    import subprocess
    subprocess.run([sys.executable, "-m", "pytest", __file__, "-v", "-s"])