#!/usr/bin/env python3
"""Test PHIR compilation followed by execution using PECOS QIR engine.

This demonstrates the full pipeline: HUGR → PHIR → LLVM IR → Execution
"""

import json
import sys
import tempfile
from pathlib import Path

import pytest

sys.path.append("python/quantum-pecos/src")

from pecos_rslib import (
    compile_hugr_via_phir,
    hugr_to_phir_mlir,
)

try:
    from pecos.engines.hybrid_engine import HybridEngine

    PECOS_AVAILABLE = True
except ImportError:
    PECOS_AVAILABLE = False


@pytest.mark.skipif(not PECOS_AVAILABLE, reason="PECOS not available")
def test_phir_compilation_and_execution() -> None:
    """Test compiling via PHIR and executing with PECOS."""
    # Create a simple quantum circuit HUGR (new format)
    hugr = {
        "modules": [
            {
                "version": "live",
                "metadata": {"name": "random_bit"},
                "nodes": [
                    {"parent": 0, "op": "Module"},
                    {"parent": 0, "op": "FuncDefn", "name": "main"},
                    {"parent": 1, "op": "Input"},
                    {"parent": 1, "op": "Output"},
                    {"parent": 1, "op": "Extension", "name": "QAlloc"},
                    {"parent": 1, "op": "Extension", "name": "H"},
                    {"parent": 1, "op": "Extension", "name": "MeasureFree"},
                ],
                "edges": [
                    [[2, 0], [4, 0]],
                    [[4, 0], [5, 0]],
                    [[5, 0], [6, 0]],
                    [[6, 0], [3, 0]],
                ],
            },
        ],
        "extensions": [],
    }

    hugr_json = json.dumps(hugr)

    # Convert to PHIR
    phir_mlir = hugr_to_phir_mlir(hugr_json, debug_output=False, optimization_level=2)
    print("\nGenerated PHIR:")
    print(phir_mlir)

    # Try to compile to LLVM IR
    try:
        llvm_ir = compile_hugr_via_phir(
            hugr_json,
            debug_output=False,
            optimization_level=2,
            target_triple=None,
        )
        print("\nGenerated LLVM IR (first 500 chars):")
        print(llvm_ir[:500] + "..." if len(llvm_ir) > 500 else llvm_ir)

        # Save LLVM IR to a temporary file
        with tempfile.NamedTemporaryFile(mode="w", suffix=".ll", delete=False) as f:
            f.write(llvm_ir)
            llvm_file = Path(f.name)

        try:
            # Note: The LLVM IR generated by PHIR uses standard QIR function names
            # which should be compatible with PECOS's QIR runtime

            # Verify the LLVM IR was generated correctly
            assert llvm_file.exists()
            assert llvm_file.stat().st_size > 0

            # Verify it contains expected QIR functions
            llvm_content = llvm_file.read_text()
            assert "@__quantum__rt__qubit_allocate" in llvm_content
            assert "@__quantum__qis__h__body" in llvm_content
            assert "@__quantum__qis__m__body" in llvm_content  # Standardized to m__body
            assert (
                "define i32 @main()" in llvm_content
            )  # PHIR uses i32 for measurements

            print(f"\n[PASS] Successfully compiled and saved LLVM IR to {llvm_file}")

            # TODO: To fully execute this, we would need to:
            # 1. Use pecos_rslib's PhirLlvmEngine with the generated LLVM file
            # 2. Or integrate with PECOS's existing QIR execution infrastructure

        finally:
            # Clean up
            if llvm_file.exists():
                llvm_file.unlink()

    except RuntimeError as e:
        if "mlir-opt" in str(e) or "MLIR" in str(e):
            pytest.skip("MLIR tools not available")
        else:
            raise


def test_bell_state_phir_analysis() -> None:
    """Analyze a Bell state circuit compiled via PHIR."""
    hugr = {
        "modules": [
            {
                "version": "live",
                "metadata": {"name": "bell_state"},
                "nodes": [
                    {"parent": 0, "op": "Module"},
                    {"parent": 0, "op": "FuncDefn", "name": "main"},
                    {"parent": 1, "op": "Input"},
                    {"parent": 1, "op": "Output"},
                    {"parent": 1, "op": "Extension", "name": "QAlloc"},
                    {"parent": 1, "op": "Extension", "name": "QAlloc"},
                    {"parent": 1, "op": "Extension", "name": "H"},
                    {"parent": 1, "op": "Extension", "name": "CX"},
                    {"parent": 1, "op": "Extension", "name": "MeasureFree"},
                    {"parent": 1, "op": "Extension", "name": "MeasureFree"},
                ],
                "edges": [
                    [[2, 0], [4, 0]],
                    [[2, 0], [5, 0]],
                    [[4, 0], [6, 0]],
                    [[6, 0], [7, 0]],
                    [[5, 0], [7, 1]],
                    [[7, 0], [8, 0]],
                    [[7, 1], [9, 0]],
                    [[8, 0], [3, 0]],
                    [[9, 0], [3, 1]],
                ],
            },
        ],
        "extensions": [],
    }

    hugr_json = json.dumps(hugr)

    # Compile via PHIR
    try:
        llvm_ir = compile_hugr_via_phir(
            hugr_json,
            debug_output=False,
            optimization_level=2,
            target_triple=None,
        )

        # Analyze the generated LLVM IR
        # Count quantum operations (only calls, not declarations)
        # PHIR uses i64 for qubit handles, not i8*
        qubit_allocs = llvm_ir.count("call i64 @__quantum__rt__qubit_allocate")
        h_gates = llvm_ir.count("call void @__quantum__qis__h__body")
        cnot_gates = llvm_ir.count(
            "call void @__quantum__qis__cx__body",
        )  # HUGR uses cx, not cnot
        measurements = llvm_ir.count(
            "call i32 @__quantum__qis__m__body",
        )  # Standardized to m__body, returns i32

        print("\nBell State LLVM IR Analysis:")
        print(f"- Qubit allocations: {qubit_allocs}")
        print(f"- Hadamard gates: {h_gates}")
        print(f"- CNOT gates: {cnot_gates}")
        print(f"- Measurements: {measurements}")

        # Verify expected counts
        assert qubit_allocs == 2, "Should allocate 2 qubits"
        assert h_gates == 1, "Should have 1 Hadamard gate"
        assert cnot_gates == 1, "Should have 1 CNOT gate"
        assert measurements == 2, "Should have 2 measurements"

        print("\n[PASS] Bell state circuit compiled correctly via PHIR")

    except RuntimeError as e:
        if "mlir-opt" in str(e) or "MLIR" in str(e):
            pytest.skip("MLIR tools not available")
        else:
            raise


if __name__ == "__main__":
    # Run tests directly
    import subprocess

    subprocess.run([sys.executable, "-m", "pytest", __file__, "-v", "-s"], check=False)
